"""StillDone Planning package.

Defines planner contracts, candidate action proposals, symbolic target references,
and strict deserialization boundaries for non-authoritative model output.
"""

from stilldone.planning.contracts import (
    ACTION_SYMBOLIC_TARGET_COMPATIBILITY,
    FORBIDDEN_AUTHORITY_AND_FACT_FIELDS,
    FORBIDDEN_PROVIDER_ID_FIELDS,
    MAX_EXPLANATION_STRING_LENGTH,
    MAX_INTENT_STRING_LENGTH,
    MAX_PLAN_STEPS,
    MAX_PLANNER_JSON_BYTES,
    MAX_SYMBOLIC_TARGET_LENGTH,
    PLANNER_ACTION_VOCABULARY,
    PLANNER_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    CandidateActionProposal,
    CandidatePlanProposal,
    DuplicateKeyError,
    EmptyPlanError,
    IncompatibleSymbolicTargetError,
    InvalidIntentError,
    MissingRequiredFieldError,
    ModelAuthorityInjectionError,
    OversizedIntentError,
    OversizedJsonPayloadError,
    OversizedPlanError,
    OversizedStringError,
    PlannerContractError,
    PlannerInput,
    PlannerMissionBindingError,
    PlannerTypeError,
    PlannerValueError,
    ProviderIdentifierInjectionError,
    SymbolicTargetRef,
    UnknownActionTypeError,
    UnknownFieldPolicyError,
    UnknownSymbolicTargetError,
    UnsupportedSchemaVersionError,
    get_candidate_plan_json_schema,
    parse_candidate_plan_for_input,
    validate_candidate_action_parameters,
)

__all__ = [
    "ACTION_SYMBOLIC_TARGET_COMPATIBILITY",
    "FORBIDDEN_AUTHORITY_AND_FACT_FIELDS",
    "FORBIDDEN_PROVIDER_ID_FIELDS",
    "MAX_EXPLANATION_STRING_LENGTH",
    "MAX_INTENT_STRING_LENGTH",
    "MAX_PLAN_STEPS",
    "MAX_PLANNER_JSON_BYTES",
    "MAX_SYMBOLIC_TARGET_LENGTH",
    "PLANNER_ACTION_VOCABULARY",
    "PLANNER_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "CandidateActionProposal",
    "CandidatePlanProposal",
    "DuplicateKeyError",
    "EmptyPlanError",
    "IncompatibleSymbolicTargetError",
    "InvalidIntentError",
    "MissingRequiredFieldError",
    "ModelAuthorityInjectionError",
    "OversizedIntentError",
    "OversizedJsonPayloadError",
    "OversizedPlanError",
    "OversizedStringError",
    "PlannerContractError",
    "PlannerInput",
    "PlannerMissionBindingError",
    "PlannerTypeError",
    "PlannerValueError",
    "ProviderIdentifierInjectionError",
    "SymbolicTargetRef",
    "UnknownActionTypeError",
    "UnknownFieldPolicyError",
    "UnknownSymbolicTargetError",
    "UnsupportedSchemaVersionError",
    "get_candidate_plan_json_schema",
    "parse_candidate_plan_for_input",
    "validate_candidate_action_parameters",
]
